# Generated by Django 4.2.16 on 2026-07-31 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('issuer', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('servicenow', 'ServiceNow'), ('cloud', 'Cloud'), ('programming', 'Programming'), ('other', 'Other')], default='other', max_length=20)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('verification_url', models.URLField(blank=True)),
                ('badge_image', models.ImageField(blank=True, upload_to='certifications/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-date_earned'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=300)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(max_length=300)),
                ('graduation_year', models.PositiveIntegerField()),
                ('gpa', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-graduation_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Overview description of the role')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of key responsibilities')),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievements')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Technologies used')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('professional_summary', models.TextField(help_text='Brief professional summary for hero section')),
                ('about_me', models.TextField(help_text='Detailed about me narrative')),
                ('hero_tagline', models.CharField(blank=True, help_text='Impactful hero statement', max_length=500)),
                ('hero_subtitles', models.TextField(blank=True, help_text='Comma-separated typing animation texts')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('certifications_count', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField(help_text='Detailed project overview')),
                ('problem_statement', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features')),
                ('challenges', models.JSONField(blank=True, default=list, help_text='Challenges faced and solutions')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Technologies used')),
                ('architecture', models.TextField(blank=True, help_text='Architecture description')),
                ('lessons_learned', models.TextField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='projects/heroes/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbnails/')),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accent_color', models.CharField(default='#6C63FF', help_text='Accent color hex', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'SEO Setting',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Databases'), ('cloud', 'Cloud & DevOps'), ('enterprise', 'Enterprise Platforms'), ('state', 'State Management'), ('soft', 'Soft Skills')], max_length=20)),
                ('proficiency', models.PositiveIntegerField(default=75, help_text='Proficiency level 0-100')),
                ('icon_class', models.CharField(blank=True, help_text='Icon class or SVG identifier', max_length=100)),
                ('color', models.CharField(blank=True, help_text='Hex color for skill card', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X'), ('email', 'Email'), ('website', 'Website'), ('stackoverflow', 'Stack Overflow'), ('medium', 'Medium'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'ordering': ['order'],
            },
        ),
    ]
